# COMO GENERAR EL AMBIENTE
# conda env create -f environment2.yml
# conda activate tarea-3
name: tarea-3
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - openai
      - langchain
      - langchain-core
      - langchain-community
      - langchain-openai 
      - faiss-cpu
      - streamlit
      - streamlit-chat
      - tiktoken
      - requests
      - beautifulsoup4
      - python-dotenv
      - google-api-python-client>=2.100.0 